### ISSUE TITLE
Get Structure

### ISSUE THREAD

**Issue by SuMineLee** [SuMineLee/OES_L2DSR#21]
About ZenHub Structure

**Comment by LSJnn** [comment]
<b>Structure</b>

GitHub 안에서 GitHub 환경과 직접적으로 연결된 유일한 Agile Project Management tool/
PR과 이슈를 편하게 연동할 수 있다..GitHub Issue와 PR을 기반으로 프로젝트를 계획하고 트래킹한다.
!![ZenHub summary.png](https://images.zenhubusercontent.com/6282fd274c9dfdcd3cef7ded/15737e6c-d16c-4119-9bed-5e5bb1b5ca23)

Issue가 업데이트되고 PR이 발생할 때마다 GitHub와 ZenHub가 연결된다.
![ZenHub summary2.png](https://images.zenhubusercontent.com/6282fd274c9dfdcd3cef7ded/00ac69d6-9631-4910-9b4c-bde4e27de422)

GitHub와의 별도 연동없이 GitHub의 저장소를 쉽게 공유할 수 있다.
Workspace 를 나눠 조직의 각 부서/팀이 필요한 이슈만 볼 수 있도록 구분했고.
![ZenHub summary4.png](https://images.zenhubusercontent.com/6282fd274c9dfdcd3cef7ded/53aef47c-f4b6-41d7-ab28-07f653b9eb0b)
![image.png](https://images.zenhubusercontent.com/6282fd274c9dfdcd3cef7ded/43692f98-1d13-44e0-8328-8bf429080d4d)
PR과 이슈를 간편하게 연동할 수 있다.


https://www.youtube.com/watch?v=Qdv8CoN4EeM&list=PLFIGvQyXSp3Bg7lc3ezj4iN9rvxYAQgU5&index=4

**Comment by LSJnn** [comment]
<b>Roadmap and ZenHub  Admin</b>

Roadmap :큰 단위 - Projects/ Epic 으로 큰 범위의 일정 지정 
          - 팀 관리자가 일정 계획 및 진행 상황 확인 
Board : 담당자 진행 사항 변경 + 이슈의 상세 진행사항 확인

**Comment by LSJnn** [comment]
<b>PR</b>

PR 이슈 연동 시 
내용에
closes #이슈 번호 혹은 PR 후 Connect Issue.

**Comment by LSJnn** [comment]
QNA
https://help.zenhub.com/support/solutions/articles/43000037261-github-permissions-and-access-in-zenhub
(Common permission/access questions)


1.다수의 repo 연결해도 사용자들은 각자  권한이 있는 repo만 접근 가능
2. REPO 연결 없이 보드랑 REPORT만도 확인 가능?
 - Read 권한 있으면 repo와 code를 보게 된다 . 
 - 과거에 Issue repo와 code repo를 따로 생성 및 병합하여 하나의 Workflow로  code repo와 병합하여 사용한 사례가 있음. 이경우 code repo에 권한이 없으면 코드 보지 못하게 구현됨.
3. 권한 변경해도 적용이 안됨.
 - 3시간 주기로 권한 확인됨. 브라우저의 전부 삭제 후 재시도 필요
