### ISSUE TITLE
Get Workflow

### ISSUE THREAD

**Issue by SuMineLee** [SuMineLee/OES_L2DSR#22]

**Comment by LSJnn** [comment]
Workflow란 하나의 워크스페이스가 갖는 파이프라인 흐름이다.
각각의 워크스페이스가 갖는 워크플로우를 연결할 수 있다.

A 워크스페이스에서의 파이프라인을 B 워크스페이스에서의 파이프라인으로 연결 및 연동시켜
이슈의 상태를 자동으로 변경할 수 있다.

ZenHub 에서는 워크플로우를 각 부서/팀의 맞게 설정하고
팀간에 워크플로우를 각자의 팀에 맞게 연동시켜 하나의 업무(issue)의 진행상황을 각자의 팀에 맞게 볼 수 있다.




![image.png](https://images.zenhubusercontent.com/6282fd274c9dfdcd3cef7ded/d88447ad-052e-446b-ac3a-fdf679ec7c2a
)

동일한 이슈를 처리하기 위한 전체적인 협업 흐름을 볼 수 있음. 
각 팀/부서는 자신의 진행 상황에 맞게 업무를 진행하면서 다른 부서의 실시간 진행 상황을 볼 수 있다.

![image.png](https://images.zenhubusercontent.com/6282fd274c9dfdcd3cef7ded/24f4fc74-4e98-4add-abde-97c5105951e2)
