### ISSUE TITLE
Get common workflow Sample

### ISSUE THREAD

**Issue by SuMineLee** [SuMineLee/OES_L2DSR#23]

**Comment by LSJnn** [comment]
![image.png](https://images.zenhubusercontent.com/6282fd274c9dfdcd3cef7ded/9c858300-bc6a-454b-b8be-480f19277f83)


![image.png](https://images.zenhubusercontent.com/6282fd274c9dfdcd3cef7ded/1e357f45-73d9-4a6d-8ada-ef9861563dd9)
